### ISSUE TITLE
OSError: /usr/lib64/libnetsnmphelpers.so.10: undefined symbol: snmp_free_var

### ISSUE THREAD

**Issue by andrewegel** [pief/python-netsnmpagent#15]
Hi Pieter-

This is a shot in the dark here, but I'm encountering an issue with loading the netsnmp shared libraries in python, and I thought maybe you had some insight:

```
>>> ctypes.CDLL("libnetsnmphelpers.so.10")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.6/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libnetsnmphelpers.so.10: undefined symbol: snmp_free_var
```

Yet that symbol exists in that library:

```
# readelf -Ws  /usr/lib64/libnetsnmphelpers.so.10 | grep snmp_free_var
    12: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND snmp_free_var
    56: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND snmp_free_varbind
```

I've tried it with ctypes.RTLD_GLOBAL set to the mode, but that doesn't do anything.

Here is the version of the OS and library:

```
# cat /etc/redhat-release 
CentOS release 5.8 (Final)
# rpm -q net-snmp
net-snmp-5.3.2.2-17.el5_8.1
```

Interestingly though, it works on CentOS 6.x

```
>>> ctypes.cdll.LoadLibrary(ctypes.util.find_library("netsnmphelpers"))
<CDLL 'libnetsnmphelpers.so.20', handle 9d7890 at 7fe1caf76690>

# cat /etc/redhat-release 
CentOS release 6.5 (Final)
# rpm -q net-snmp
net-snmp-5.5-49.el6_5.1.x86_64
```
Any insight would help, but I understand if this cannot be helped.

**Comment by pief** [comment]
Would this still be an issue?

**Comment by andrewegel** [comment]
So long ago - Feel free to close.
